### ISSUE TITLE
Delete fork of neil

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/neil#17]
https://github.com/tomjaguarpaw/neil is a fork of this repo by @tomjaguarpaw. This ticket is for @tomjaguarpaw to raise all the issues he has with this version, so they can be eliminated, with the end goal of deleting the fork and using a common code base.

**Comment by ndmitchell** [comment]
Issues:

- [ ] Don't error on warnings (Tom should remove the warnings from his code)
- [ ] Repo name is haskell-opaleye not opaleye (Tom needs to decide if he will change or not, if not, I'll update the script)
- [ ] Readme check is disabled
- [ ] Travis script check is disabled
- [ ] .ghci script check is disabled

**Comment by ndmitchell** [comment]
I leave it to @tomjaguarpaw to decide if he wants to remove his fork and do some merging. In general, `neil` is not a robust or super supported tool - it's deliberately named after its author since it doesn't really seek to exist outside of his service. That said, I'm not adverse to pull requests that help everyone.

**Comment by tomjaguarpaw** [comment]
I'm not consciously using `neil` at the moment but will return to address these issues if and when I start again.
