### ISSUE TITLE
Error: "curl: (18) transfer closed with outstanding read data remaining"

### ISSUE THREAD

**Issue by orome** [ndmitchell/neil#22]
After having this work perfectly for me, it's failing with 

> Error: "curl: (18) transfer closed with outstanding read data remaining"

All I've done is update the version of my package on Hackage.

**Comment by ndmitchell** [comment]
No real idea - perhaps print out the command line it's using, try it manually, and see what it says? I've not seen that error before. The other possibility is that Hackage is currently having a wobble, it isn't he most reliable, so wait an hour and try again.

**Comment by orome** [comment]
I'll go with the "wobble" theory for now and get back to you.

**Comment by orome** [comment]
"Wobble" indeed. They've [changed over to 7.10.2](https://github.com/haskell/hackage-server/issues/419#issuecomment-143729170), which completely solves my doc building problems and might account for the error I'm getting (and continue to get).

**Comment by ndmitchell** [comment]
Great, I'll close this then. Let's hope for fewer wobbles in future.
