### ISSUE TITLE
grab probably shouldn't be case sensitive

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/neil#26]
`grab` is case sensitive and probably shouldn't be

https://github.com/ndmitchell/neil/blob/master/src/Cabal.hs#L225

**Comment by ndmitchell** [comment]
The fact cabal isn't case sensitive is a massive misfeature. Think of a good language. It should have a canonical form. Given it uses kebab casing, lower case is the only thing that makes sense. Part of the idea of grab is to enforce that.

**Comment by tomjaguarpaw** [comment]
That's reasonable.

**Comment by ndmitchell** [comment]
Do I not have a check somewhere that all cabal fields are lowercase? If I don't I should. If I do, perhaps it wants moving before the first grab.

**Comment by tomjaguarpaw** [comment]
That check is "Incorrect declaration style" and happens at https://github.com/ndmitchell/neil/blob/master/src/Cabal.hs#L245, after `grab`.

**Comment by ndmitchell** [comment]
Fixed as part of #27.
