### ISSUE TITLE
grab should warn on missing fields

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/neil#27]
If a field is missing, `grab` should explicitly say so.  The error

    neil: : openFile: does not exist (No such file or directory)

when grab looks for `license-file` but the field is actually `licence-File` is really confusing.

https://github.com/ndmitchell/neil/blob/master/src/Cabal.hs#L225

**Comment by tomjaguarpaw** [comment]
Other discussion https://github.com/ndmitchell/neil/issues/26#issuecomment-222297722

**Comment by ndmitchell** [comment]
I just made a failing to read license-file pretend its "", and then all the other checks move into the right order and fire properly.
