### ISSUE TITLE
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by bonro001** [ndmitchell/neil#28]
Hello all,

I have been getting "error: RPC failed; curl 18 transfer closed with outstanding read data remaining" for a few days now when trying to update pods (1.0.1).  Here is the github command:

```
 > Git download
     $ /usr/bin/git clone https://github.com/SVGKit/SVGKit.git /var/folders/bm/3q6p4v0119xfywv1yb182w0c0000gn/T/d20160811-12646-1k9vb1h
     --template= --single-branch --depth 1 --branch 2.x
     Cloning into '/var/folders/bm/3q6p4v0119xfywv1yb182w0c0000gn/T/d20160811-12646-1k9vb1h'...
     error: RPC failed; curl 18 transfer closed with outstanding read data remaining
     fatal: The remote end hung up unexpectedly
     fatal: early EOF
     fatal: index-pack failed

[!] Error installing SVGKit
[!] /usr/bin/git clone https://github.com/SVGKit/SVGKit.git /var/folders/bm/3q6p4v0119xfywv1yb182w0c0000gn/T/d20160811-12646-1k9vb1h --template= --single-branch --depth 1 --branch 2.x

Cloning into '/var/folders/bm/3q6p4v0119xfywv1yb182w0c0000gn/T/d20160811-12646-1k9vb1h'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

```

I have even gone as far as spinning up a new OS X instance (10.11.5), full git and pods install, new SSH key (I have access to this branch).  Same thing.

Looking for any suggestion for a next step.

Thanks in advance!

**Comment by ndmitchell** [comment]
I'm not sure what this has to do with this project? Are you using the `neil` command anywhere?

**Comment by bonro001** [comment]
Oh shoot, thought this was the github support page, my bad!!!

**Comment by hashimyousaf** [comment]
I hope , this will be helpful for you .Thanks
http://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

**Comment by suwenmaw** [comment]
thanks!

**Comment by Muthenya** [comment]
Mine got resolved by simply getting a better internet connection and the cloning was successful.

**Comment by PraveenReddyPasala** [comment]
> I hope , this will be helpful for you .Thanks
> http://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

Above one worked for me. Thank You.

**Comment by ghasemikasra39** [comment]
same here

**Comment by eltonsandre** [comment]
increase http.postBuffer
`git config --global http.postBuffer 524288000`

**Comment by Hamza-Meknassi** [comment]
i've the same issue with 15Mbs !

**Comment by BoasE** [comment]
@Hamza-Meknassi  how have you solvedi t?

**Comment by nvispute** [comment]
Even i started facing this issue in last few weeks, i guess my ISP updated / Upgraded there firewalls or something the upload has dropped from 25 mbps to 1 mbps and keeps on going up and down depending on the requests and since then i have started facing error while pushing the code to online repo

**Comment by BrunoCerberus** [comment]
having the same problem

**Comment by j-akbar** [comment]
please try this :
$ git clone [url] --depth 1
$ cd [folder_file]
$ git fetch --unshallow

**Comment by chandanp619** [comment]
I got this issue solved with the following 3 commands.

git config --global http.postBuffer 524288000

git config --global http.maxRequestBuffer 524288000

git config --global core.compression 0

**Comment by coderkaziarif** [comment]
Need helped regarding this issues....
Writing objects: 100% (27/27), 7.08 MiB | 80.57 MiB/s, done.    
Total 27 (delta 2), reused 0 (delta 0), pack-reused 0
**error: RPC failed; curl 18 transfer closed with outstanding read data remaining**
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by ndmitchell** [comment]
@coderkaziarif - this is not the right place to raise this issue and I have nothing to do with the issue you are describing

**Comment by ashishrai8880** [comment]
Writing objects: 100% (27/27), 7.08 MiB | 80.57 MiB/s, done.
Total 27 (delta 2), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

I have also getting this error even file size is less than 10 MB , when file size is below 2 MB then only my code push to github
Please Please help someone !

**Comment by ashishrai8880** [comment]
> 

i am also gettin same issue , how did you solve brother . Please help

**Comment by ArielQ-MDZ** [comment]
I tried everything and I did not have a positive result since it was not a Gitlab configuration but NGIX.
I found the solution here https://gist.github.com/enqtran/10e33674701967edd12c3cf224c835f8

**Comment by cg-tester** [comment]
@chandanp619 

I had got the same issue and solved successfully with your 3 git config commands.  Great !

**Comment by lycuongjr** [comment]
> @chandanp619
> 
> I had got the same issue and solved successfully with your 3 git config commands. Great !

it don't work for me.

**Comment by i4seeu** [comment]
I am facing the same challenge but non of the suggested fix works on my end

**Comment by halidi-hamidu** [comment]
I  Tried to fetch  git clone --depth=1 https://github.com/odoo/odoo.git -b 17.0 thne its is throw this error 


error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 2733 bytes of body are still expected
09:30:41.592196 pkt-line.c:80           packet:          git> 0002
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
