### ISSUE TITLE
Get the actual name of the GitHub repository

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/neil#34]
I came up with this, which gets the actual name of the GitHub repository by (essentially) reading it out of the `homepage` field of the Cabal file.  I need this because `opaleye`'s repository is called `haskell-opaleye`.  My code is a horrible hack but it just about works.  I'm sure it can be improved.  Are you interested in merging something like this?

https://github.com/ndmitchell/neil/compare/master...tomjaguarpaw:master#diff-030c1b9cbeb9b30d228469eaff6892f9R282

**Comment by ndmitchell** [comment]
I'll certainly merge something along these lines - I'm very keen to merge something. I'll take a look at the code in a few days.

**Comment by tomjaguarpaw** [comment]
This code works for me but it's not very robust.  We can probably come up with something better.

**Comment by tomjaguarpaw** [comment]
This was fixed by https://github.com/tomjaguarpaw/neil/commit/f08459ff929a998b260dcc41ff70c9b9540cdcd0
