### ISSUE TITLE
Need to choose precise repository and commit to use

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/neil#35]
I've got pretty close to removing all the differences between our two versions of `neil`: https://github.com/ndmitchell/neil/compare/master...tomjaguarpaw:master

What I'd really like now is the ability to clone `neil` from a specific repository *and* commit and use that repository and commit consistently throughout the rest of the Travis processing. 

What do you think?

**Comment by ndmitchell** [comment]
I don't know what you mean "clone `neil` from a specific repository"? Do you mean you want to use tomjaguarpaw/neil? Wouldn't you switch to ndmitchell/neil?

**Comment by tomjaguarpaw** [comment]
Yes, ideally I'd be on `ndmitchell/neil` `master` but there may be times I need to fork and use a specific other repo and branch/commit.

**Comment by tomjaguarpaw** [comment]
This was fixed by https://github.com/ndmitchell/neil/pull/40
