### ISSUE TITLE
Add one 'X' to run.sh's mktemp template

### ISSUE THREAD

**Issue by Kritzefitz** [ndmitchell/neil#43]
Hi,

as seen in [this log](https://gitlab.com/Kritzefitz/concurrent-accept/-/jobs/170348243), using run.sh on a busybox shell fails, with the error message `mktemp: Invalid argument`. Adding another 'X' to the template would fix this problem, as that is apparently the magical required minimum.

**Comment by ndmitchell** [comment]
Thanks for the report. PR most welcome.
