### ISSUE TITLE
Why Cabal v1-style?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ndmitchell/neil#49]
Is there a particular reason that `neil` uses Cabal v1-style commands?  If it's just because no one's upgraded to v2-style yet then please let me know as I will attempt to do that.

https://github.com/ndmitchell/neil/blob/b8ebe3986ec2895a34ed3b26200ffdea8bb755ff/src/Cabal.hs#L174-L175

**Comment by ndmitchell** [comment]
No one has upgraded it, and it works well, so I haven't bothered to upgrade. I also still use v1-style commands on my home machine and have a global package database, so it doesn't cause me any difficulties. If someone wants to upgrade, I'd be very happy though.

**Comment by tomjaguarpaw** [comment]
(I'm particularly interested in using v2-style for Travis because v1-style has difficulty reinstalling packages when necessary)

**Comment by ndmitchell** [comment]
I guess i've always been careful to ensure that package reinstalls weren't required. It would also be useful if the initial compile of `neil` and the subsequent compile of whatever we build next shares the `extra` library between them - but given the library is small, not essential.

**Comment by tomjaguarpaw** [comment]
Yes, I use cached Travis `.ghc` and `.cabal` directories to reduce build times so maybe occasionally clearing those comes with the territory.

**Comment by ndmitchell** [comment]
Cool - go for it - I'd welcome a PR.

**Comment by tomjaguarpaw** [comment]
I decided that purging my caches was the easiest solution for now.  If I regularly run into this problem then I will investigate v2-style.

**Comment by tomjaguarpaw** [comment]
> I also still use v1-style commands on my home machine and have a global package database

This is completely tangential to the original issue, but I'm very curious: how do you deal with package conflicts with a v1-style global package database?  Do you have to occasionally delete all your packages and rebuild everything, or do you have another strategy?

**Comment by ndmitchell** [comment]
When things go wrong I just reinstall. It doesn't happen that often, and reinstalling isn't too painful.
